//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSystem.Client.PaymentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/AuctionSystem.Models")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AuctionSystem.Client.PaymentServiceReference.PaymentType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentTypeCode {
            get {
                return this.PaymentTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeCodeField, value) != true)) {
                    this.PaymentTypeCodeField = value;
                    this.RaisePropertyChanged("PaymentTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuctionSystem.Client.PaymentServiceReference.PaymentType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentType", Namespace="http://schemas.datacontract.org/2004/07/AuctionSystem.Models.Enums")]
    public enum PaymentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayPal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreditCard = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankTransfer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AmazonPayment = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDto", Namespace="http://schemas.datacontract.org/2004/07/AuctionSystem.Models.DTOs")]
    [System.SerializableAttribute()]
    public partial class PaymentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AuctionSystem.Client.PaymentServiceReference.PaymentType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentTypeCode {
            get {
                return this.PaymentTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeCodeField, value) != true)) {
                    this.PaymentTypeCodeField = value;
                    this.RaisePropertyChanged("PaymentTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuctionSystem.Client.PaymentServiceReference.PaymentType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentServiceReference.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPaymentService/AddPayment")]
        void AddPayment(AuctionSystem.Client.PaymentServiceReference.Payment payment, int userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPaymentService/AddPayment")]
        System.Threading.Tasks.Task AddPaymentAsync(AuctionSystem.Client.PaymentServiceReference.Payment payment, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetPayment", ReplyAction="http://tempuri.org/IPaymentService/GetPaymentResponse")]
        AuctionSystem.Client.PaymentServiceReference.PaymentDto GetPayment(int paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetPayment", ReplyAction="http://tempuri.org/IPaymentService/GetPaymentResponse")]
        System.Threading.Tasks.Task<AuctionSystem.Client.PaymentServiceReference.PaymentDto> GetPaymentAsync(int paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/DeletePayment", ReplyAction="http://tempuri.org/IPaymentService/DeletePaymentResponse")]
        bool DeletePayment(int paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/DeletePayment", ReplyAction="http://tempuri.org/IPaymentService/DeletePaymentResponse")]
        System.Threading.Tasks.Task<bool> DeletePaymentAsync(int paymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePayment", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentResponse")]
        bool UpdatePayment(AuctionSystem.Client.PaymentServiceReference.PaymentDto payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePayment", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentResponse")]
        System.Threading.Tasks.Task<bool> UpdatePaymentAsync(AuctionSystem.Client.PaymentServiceReference.PaymentDto payment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : AuctionSystem.Client.PaymentServiceReference.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<AuctionSystem.Client.PaymentServiceReference.IPaymentService>, AuctionSystem.Client.PaymentServiceReference.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddPayment(AuctionSystem.Client.PaymentServiceReference.Payment payment, int userId) {
            base.Channel.AddPayment(payment, userId);
        }
        
        public System.Threading.Tasks.Task AddPaymentAsync(AuctionSystem.Client.PaymentServiceReference.Payment payment, int userId) {
            return base.Channel.AddPaymentAsync(payment, userId);
        }
        
        public AuctionSystem.Client.PaymentServiceReference.PaymentDto GetPayment(int paymentId) {
            return base.Channel.GetPayment(paymentId);
        }
        
        public System.Threading.Tasks.Task<AuctionSystem.Client.PaymentServiceReference.PaymentDto> GetPaymentAsync(int paymentId) {
            return base.Channel.GetPaymentAsync(paymentId);
        }
        
        public bool DeletePayment(int paymentId) {
            return base.Channel.DeletePayment(paymentId);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePaymentAsync(int paymentId) {
            return base.Channel.DeletePaymentAsync(paymentId);
        }
        
        public bool UpdatePayment(AuctionSystem.Client.PaymentServiceReference.PaymentDto payment) {
            return base.Channel.UpdatePayment(payment);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePaymentAsync(AuctionSystem.Client.PaymentServiceReference.PaymentDto payment) {
            return base.Channel.UpdatePaymentAsync(payment);
        }
    }
}
